### ISSUE TITLE
Error during install rails-api-base- Your Ruby version is 1.9.3, but your Gemfile specified 2.3.0

### ISSUE THREAD

**Issue by freemannguyen** [jordifierro/rails-api-base#2]
Hi @jordifierro 
I am trying to install rails-api-base but I have a probleam durring install it. I just follow below steps.

Step 1
`git clone git://github.com/jordifierro/rails-api-base.git --origin rails-api-base rails_api
`
Step 2: 

`cd rails_api/`

Step 3: 

```
postgres@freeman:~/rails_api$ ./bin/rename_project rails_api
sed: can't read : No such file or directory
sed: can't read : No such file or directory
Project name changed and README.md content emptied
```
Step 4: 

```
postgres@freeman:~/rails_api$ ./bin/remove_notes
Notes related code files removed
```
Step 5:

```
postgres@freeman:~/rails_api$ ./bin/create_psql_user rails_api
CREATE ROLE
ALTER ROLE
```
Step 6: 

```
postgres@freeman:~/rails_api$ ./bin/setup
== Installing dependencies ==
Your Ruby version is 1.9.3, but your Gemfile specified 2.3.0
Your Ruby version is 1.9.3, but your Gemfile specified 2.3.0

== Command ["bundle install"] failed ==
```
I've search on the web but still not solved. Could you please take a look. Thanks you so much

**Comment by jordifierro** [comment]
Hi @freemannguyen, sorry for the delay in replying.

You must update your ruby version to 2.3.0. If you are working on multiple projects try [rvm](https://rvm.io/) or [rbenv](http://rbenv.org/) to manage ruby versions for different development environments.

Hope it helps!
