### ISSUE TITLE
API Versioning issue after V9

### ISSUE THREAD

**Issue by sagarkt** [jordifierro/rails-api-base#4]
https://github.com/jordifierro/rails-api-base/blob/96931e446be8d0cd10f0886eaa091ae8f6d69f7b/lib/api_constraints.rb#L11

This matches V1 with V1[x] - x is anything.

This makes API version to lock at V9 because mentioning any new version makes it point V1.

Fix -> [PR 5](https://github.com/jordifierro/rails-api-base/pull/5)

**Comment by jordifierro** [comment]
Merged! Thanks 👍
